### ISSUE TITLE
Add the Maui.Graphics website to the repository details

### ISSUE THREAD

**Issue by bmitc** [dotnet/Microsoft.Maui.Graphics#463]
I wasn't finding information in the README how to actually use the library, but I found the [Maui.Graphics website](https://maui.graphics/), which also links to the [official documentation](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/graphics/).

I think the Maui.Graphics website should be put in the repository details, and that the documentation should be linked to from the README.

**Comment by swharden** [comment]
Hi @bmitc and project owners (@jonlipsky)

I registered https://maui.graphics a while ago because I kept trying to search for documentation about this library but `.graphics` is a top level domain so my browser would try to go to that URL and timeout. To be clear, I'm an open source maintainer who enjoys making .NET apps, and I'm not affiliated with Microsoft.

At one time I considered putting quickstarts and code examples on the site, but I don't think I'm the best person to create/maintain/represent idiomatic use cases for this library at this time, so I am currently just linking to the best official documentation page I'm aware of.

If this group has a better recommendation for what should be at that URL, I welcome the input!

PS: I noticed when people tweet the phrase "maui.graphics" it automatically hyperlinks to that page (e.g., https://twitter.com/jonlipsky/status/1529185387846873088)

PPS: I heard @jamesmontemagno mention the domain on [Merge Conflict episode #302](https://www.mergeconflict.fm/302), so I welcome input from him too

**Comment by bmitc** [comment]
Thanks for the heads up on that @swharden. It looked so nice, that I just assumed it was official. 🙂 So yea, up to the project maintainers on that aspect.

After actually reading the official documentation, it's only from the perspective of using Maui.Graphics from Maui itself, but I think that at a minimum it should be included somewhere in the README.

**Comment by swharden** [comment]
> Thanks for the heads up on that @swharden. It looked so nice, that I just assumed it was official.

haha, thanks! 🚀

> After actually reading the official documentation, it's only from the perspective of using Maui.Graphics from Maui itself

I'm not aware of any official documentation about how to use Maui.Graphics in non-Maui apps. The topic seems highly relevant since .NET 6 [deprecated cross-platform support for System.Drawing.Common](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) and one of Microsoft's [recommended actions](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action) is to use this library instead.

I put some Maui.Graphics Quickstart pages on [C# Data Visualization](https://swharden.com/csdv/) showing how I use this library in Console, WinForms, and WPF apps that you may find useful.

**Comment by bmitc** [comment]
@jonlipsky Thanks for the information! I was at least hoping that is the case. So as to not distract from this documentation related issue, I've posted a question regarding that in the discussions section: https://github.com/dotnet/Microsoft.Maui.Graphics/discussions/466

I've been meaning to ask that question anyway. Although I'm concerned that there's too much fragmentation for .NET graphics libraries and GUI frameworks, as mentioned here https://github.com/dotnet/Microsoft.Maui.Graphics/discussions/272, I'm still trying to do due diligence in considering all alternatives for existing .NET graphics solutions.

**Comment by bmitc** [comment]
Repository is no longer under development. See https://github.com/dotnet/Microsoft.Maui.Graphics/pull/496#issuecomment-1375104121.
