### ISSUE TITLE
Color property name changes `R` to `Red`

### ISSUE THREAD

**Issue by mattleibow** [dotnet/Microsoft.Maui.Graphics#54]
The `Color.R` -> `Color.Red` is not super different as I am not sure how many people actually use the components individually. However, this may be different enough.

But, it is worth pointing out that it _is_ different and it is also different to most other Microsoft color types out there (WPF, UWP, WinUI, WinForms, Xamarin.Forms).

iOS does not have this and they have a `GetRGBA(out r, out g, out b, out a)`

Relates to parent issue: #58

**Comment by hartez** [comment]
I personally prefer the full names, and the full names fit more closely with the framework naming guidelines. 

That said, for folks making the transition from System.Drawing, Xamarin.Forms, Windows.UI.Color, etc., this might be a small and annoying hiccup. 

Since we're talking about readonly fields, we _could_ simply add property accessors with the short names:

```
public float R => Red;
public float G => Green;
public float B => Blue;
public float A => Alpha;
```

**Comment by Redth** [comment]
Done.
